title: Hi, I'm Ibrahim
decription: An aspiring Data Analyst passionate about turning data into actionable insights. Welcome to my portfolio.
show_downloads: False
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
